"""extend_rulebook_id_to_200_chars

Revision ID: 2d895413b8b8
Revises: 011_remove_validation_rules
Create Date: 2026-02-26 23:29:12.609337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d895413b8b8'
down_revision = '011_remove_validation_rules'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_synonyms_related_dps_gin'), table_name='synonyms_glossary', postgresql_using='gin')
    op.drop_index(op.f('idx_synonyms_term_embedding'), table_name='synonyms_glossary', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (term_embedding IS NOT NULL))')
    op.drop_index(op.f('idx_term_en_gin'), table_name='synonyms_glossary', postgresql_using='gin')
    op.drop_index(op.f('idx_term_ko_gin'), table_name='synonyms_glossary', postgresql_using='gin')
    op.drop_table('synonyms_glossary')
    op.drop_index(op.f('idx_data_points_embedding'), table_name='data_points', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (embedding IS NOT NULL))')
    op.drop_index(op.f('idx_data_points_parent_indicator'), table_name='data_points', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_data_points_standard'), table_name='data_points', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_data_points_topic'), table_name='data_points', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_dp_child_dps_gin'), table_name='data_points', postgresql_using='gin')
    op.drop_index(op.f('idx_dp_equivalent_dps_gin'), table_name='data_points', postgresql_using='gin')
    op.drop_index(op.f('idx_dp_parent_indicator'), table_name='data_points', postgresql_where='((is_active = true) AND (parent_indicator IS NOT NULL))')
    op.drop_index(op.f('idx_dp_standard_category'), table_name='data_points', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_data_points_parent_indicator'), 'data_points', ['parent_indicator'], unique=False)
    op.create_index(op.f('ix_data_points_standard'), 'data_points', ['standard'], unique=False)
    op.create_index(op.f('ix_data_points_topic'), 'data_points', ['topic'], unique=False)
    op.drop_index(op.f('idx_disclosure_methods_unified_column'), table_name='disclosure_methods', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_disclosure_methods_unified_column_id'), 'disclosure_methods', ['unified_column_id'], unique=False)
    op.drop_index(op.f('idx_document_chunks_embedding'), table_name='document_chunks', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (embedding IS NOT NULL))')
    op.drop_index(op.f('idx_document_chunks_path_type'), table_name='document_chunks', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_document_chunks_standard_year'), table_name='document_chunks', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_decomposition_child_gin'), table_name='dp_decomposition_rules', postgresql_using='gin')
    op.drop_index(op.f('idx_decomposition_parent'), table_name='dp_decomposition_rules', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_financial_impact_embedding'), table_name='dp_financial_linkages', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (impact_embedding IS NOT NULL))')
    op.drop_index(op.f('idx_financial_linkages_account'), table_name='dp_financial_linkages', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_financial_linkages_dp'), table_name='dp_financial_linkages', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_glossary_embedding'), table_name='glossary', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (term_embedding IS NOT NULL))')
    op.drop_index(op.f('idx_glossary_standard'), table_name='glossary', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_glossary_standard'), 'glossary', ['standard'], unique=False)
    op.create_unique_constraint(None, 'glossary', ['term_ko'])
    op.alter_column('rulebooks', 'rulebook_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('idx_rulebooks_primary_dp_id'), table_name='rulebooks', postgresql_where='((is_active = true) AND (primary_dp_id IS NOT NULL))')
    op.drop_index(op.f('idx_rulebooks_section_embedding'), table_name='rulebooks', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (section_embedding IS NOT NULL))')
    op.drop_index(op.f('idx_rulebooks_standard_id'), table_name='rulebooks', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_rulebooks_standard_section'), table_name='rulebooks', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_rulebooks_validation_rules_gin'), table_name='rulebooks', postgresql_using='gin')
    op.create_index(op.f('ix_rulebooks_primary_dp_id'), 'rulebooks', ['primary_dp_id'], unique=False)
    op.create_index(op.f('ix_rulebooks_standard_id'), 'rulebooks', ['standard_id'], unique=False)
    op.alter_column('standards', 'section_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('idx_standards_embedding'), table_name='standards', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (section_embedding IS NOT NULL))')
    op.drop_index(op.f('idx_standards_section_type'), table_name='standards', postgresql_where='(is_active = true)')
    op.drop_constraint(op.f('uq_standard_section_name'), 'standards', type_='unique')
    op.drop_index(op.f('idx_ucm_primary_rulebook'), table_name='unified_column_mappings', postgresql_where='((is_active = true) AND (primary_rulebook_id IS NOT NULL))')
    op.drop_index(op.f('idx_ucm_primary_standard'), table_name='unified_column_mappings', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_unified_column_mappings_category_topic'), table_name='unified_column_mappings', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_unified_column_mappings_dp_ids'), table_name='unified_column_mappings', postgresql_using='gin', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_unified_column_mappings_embedding'), table_name='unified_column_mappings', postgresql_using='hnsw', postgresql_where='((is_active = true) AND (unified_embedding IS NOT NULL))')
    op.create_index(op.f('ix_unified_column_mappings_primary_rulebook_id'), 'unified_column_mappings', ['primary_rulebook_id'], unique=False)
    op.create_index(op.f('ix_unified_column_mappings_primary_standard'), 'unified_column_mappings', ['primary_standard'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_column_mappings_primary_standard'), table_name='unified_column_mappings')
    op.drop_index(op.f('ix_unified_column_mappings_primary_rulebook_id'), table_name='unified_column_mappings')
    op.create_index(op.f('idx_unified_column_mappings_embedding'), 'unified_column_mappings', ['unified_embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (unified_embedding IS NOT NULL))')
    op.create_index(op.f('idx_unified_column_mappings_dp_ids'), 'unified_column_mappings', ['mapped_dp_ids'], unique=False, postgresql_using='gin', postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_unified_column_mappings_category_topic'), 'unified_column_mappings', ['column_category', 'column_topic'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_ucm_primary_standard'), 'unified_column_mappings', ['primary_standard'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_ucm_primary_rulebook'), 'unified_column_mappings', ['primary_rulebook_id'], unique=False, postgresql_where='((is_active = true) AND (primary_rulebook_id IS NOT NULL))')
    op.create_unique_constraint(op.f('uq_standard_section_name'), 'standards', ['standard_id', 'section_name'])
    op.create_index(op.f('idx_standards_section_type'), 'standards', ['section_type'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_standards_embedding'), 'standards', ['section_embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (section_embedding IS NOT NULL))')
    op.alter_column('standards', 'section_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_rulebooks_standard_id'), table_name='rulebooks')
    op.drop_index(op.f('ix_rulebooks_primary_dp_id'), table_name='rulebooks')
    op.create_index(op.f('idx_rulebooks_validation_rules_gin'), 'rulebooks', ['validation_rules'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_rulebooks_standard_section'), 'rulebooks', ['standard_id', 'section_name'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_rulebooks_standard_id'), 'rulebooks', ['standard_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_rulebooks_section_embedding'), 'rulebooks', ['section_embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (section_embedding IS NOT NULL))')
    op.create_index(op.f('idx_rulebooks_primary_dp_id'), 'rulebooks', ['primary_dp_id'], unique=False, postgresql_where='((is_active = true) AND (primary_dp_id IS NOT NULL))')
    op.alter_column('rulebooks', 'rulebook_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'glossary', type_='unique')
    op.drop_index(op.f('ix_glossary_standard'), table_name='glossary')
    op.create_index(op.f('idx_glossary_standard'), 'glossary', ['standard'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_glossary_embedding'), 'glossary', ['term_embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (term_embedding IS NOT NULL))')
    op.create_index(op.f('idx_financial_linkages_dp'), 'dp_financial_linkages', ['dp_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_financial_linkages_account'), 'dp_financial_linkages', ['financial_account_code'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_financial_impact_embedding'), 'dp_financial_linkages', ['impact_embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (impact_embedding IS NOT NULL))')
    op.create_index(op.f('idx_decomposition_parent'), 'dp_decomposition_rules', ['parent_dp_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_decomposition_child_gin'), 'dp_decomposition_rules', ['child_dp_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_document_chunks_standard_year'), 'document_chunks', ['standard', 'fiscal_year'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_document_chunks_path_type'), 'document_chunks', ['document_path', 'document_type'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (embedding IS NOT NULL))')
    op.drop_index(op.f('ix_disclosure_methods_unified_column_id'), table_name='disclosure_methods')
    op.create_index(op.f('idx_disclosure_methods_unified_column'), 'disclosure_methods', ['unified_column_id'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_data_points_topic'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_standard'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_parent_indicator'), table_name='data_points')
    op.create_index(op.f('idx_dp_standard_category'), 'data_points', ['standard', 'category'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_dp_parent_indicator'), 'data_points', ['parent_indicator'], unique=False, postgresql_where='((is_active = true) AND (parent_indicator IS NOT NULL))')
    op.create_index(op.f('idx_dp_equivalent_dps_gin'), 'data_points', ['equivalent_dps'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_dp_child_dps_gin'), 'data_points', ['child_dps'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_data_points_topic'), 'data_points', ['topic'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_data_points_standard'), 'data_points', ['standard'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_data_points_parent_indicator'), 'data_points', ['parent_indicator'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_data_points_embedding'), 'data_points', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (embedding IS NOT NULL))')
    op.create_table('synonyms_glossary',
    sa.Column('term_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('term_ko', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('term_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('standard', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('related_dps', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('term_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('term_embedding_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('term_embedding_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('term_id', name=op.f('synonyms_glossary_pkey'))
    )
    op.create_index(op.f('idx_term_ko_gin'), 'synonyms_glossary', ['term_ko'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_term_en_gin'), 'synonyms_glossary', ['term_en'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_synonyms_term_embedding'), 'synonyms_glossary', ['term_embedding'], unique=False, postgresql_using='hnsw', postgresql_where='((is_active = true) AND (term_embedding IS NOT NULL))')
    op.create_index(op.f('idx_synonyms_related_dps_gin'), 'synonyms_glossary', ['related_dps'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
